### ISSUE TITLE
Create test for UserRepository and MessageRepository

### ISSUE THREAD

**Issue by ValentinaSukonina** [Ebyrdeu/spring_boot_library#15]
Testing repository interfaces ensures that the data access layer functions correctly, providing confidence in the application's ability to interact with the underlying database

**Comment by Ebyrdeu** [comment]
I'm not sure if this is a good idea. Similar to Lombok, Spring Boot generates code for us during the compilation stage. So, it's not really our job to test this but the Spring development team's instead. Also, it's going to be a tough thing to do because we'd need to know how it generates code and what methods it uses inside to be effective at edge testing. But if you really want to do it, go for it. I won't say no to you if you're set on doing unit testing.

**Comment by ValentinaSukonina** [comment]
You very well might be right. I found this suggestions for tests in https://courses.baeldung.com/courses/1295711/lectures/30127904 and thought about using @DataJpaTest annotation, that invokes several Spring Boot auto-configurations used in application. In this way, it closely replicates the real behavior of application. I will look on that in more details.
